# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Email(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, id_prospection: int=None, emisor: str=None, mensaje: str=None, fecha: date=None):  # noqa: E501
        """Email - a model defined in Swagger

        :param id: The id of this Email.  # noqa: E501
        :type id: int
        :param id_prospection: The id_prospection of this Email.  # noqa: E501
        :type id_prospection: int
        :param emisor: The emisor of this Email.  # noqa: E501
        :type emisor: str
        :param mensaje: The mensaje of this Email.  # noqa: E501
        :type mensaje: str
        :param fecha: The fecha of this Email.  # noqa: E501
        :type fecha: date
        """
        self.swagger_types = {
            'id': int,
            'id_prospection': int,
            'emisor': str,
            'mensaje': str,
            'fecha': date
        }

        self.attribute_map = {
            'id': 'id',
            'id_prospection': 'id_prospection',
            'emisor': 'emisor',
            'mensaje': 'mensaje',
            'fecha': 'fecha'
        }
        self._id = id
        self._id_prospection = id_prospection
        self._emisor = emisor
        self._mensaje = mensaje
        self._fecha = fecha

    @classmethod
    def from_dict(cls, dikt) -> 'Email':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Email of this Email.  # noqa: E501
        :rtype: Email
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Email.


        :return: The id of this Email.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Email.


        :param id: The id of this Email.
        :type id: int
        """

        self._id = id

    @property
    def id_prospection(self) -> int:
        """Gets the id_prospection of this Email.


        :return: The id_prospection of this Email.
        :rtype: int
        """
        return self._id_prospection

    @id_prospection.setter
    def id_prospection(self, id_prospection: int):
        """Sets the id_prospection of this Email.


        :param id_prospection: The id_prospection of this Email.
        :type id_prospection: int
        """

        self._id_prospection = id_prospection

    @property
    def emisor(self) -> str:
        """Gets the emisor of this Email.


        :return: The emisor of this Email.
        :rtype: str
        """
        return self._emisor

    @emisor.setter
    def emisor(self, emisor: str):
        """Sets the emisor of this Email.


        :param emisor: The emisor of this Email.
        :type emisor: str
        """

        self._emisor = emisor

    @property
    def mensaje(self) -> str:
        """Gets the mensaje of this Email.


        :return: The mensaje of this Email.
        :rtype: str
        """
        return self._mensaje

    @mensaje.setter
    def mensaje(self, mensaje: str):
        """Sets the mensaje of this Email.


        :param mensaje: The mensaje of this Email.
        :type mensaje: str
        """

        self._mensaje = mensaje

    @property
    def fecha(self) -> date:
        """Gets the fecha of this Email.


        :return: The fecha of this Email.
        :rtype: date
        """
        return self._fecha

    @fecha.setter
    def fecha(self, fecha: date):
        """Sets the fecha of this Email.


        :param fecha: The fecha of this Email.
        :type fecha: date
        """

        self._fecha = fecha
