# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Note(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, prospection_id: int=None, message: str=None, _date: date=None):  # noqa: E501
        """Note - a model defined in Swagger

        :param id: The id of this Note.  # noqa: E501
        :type id: int
        :param prospection_id: The prospection_id of this Note.  # noqa: E501
        :type prospection_id: int
        :param message: The message of this Note.  # noqa: E501
        :type message: str
        :param _date: The _date of this Note.  # noqa: E501
        :type _date: date
        """
        self.swagger_types = {
            'id': int,
            'prospection_id': int,
            'message': str,
            '_date': date
        }

        self.attribute_map = {
            'id': 'id',
            'prospection_id': 'prospection_id',
            'message': 'message',
            '_date': 'date'
        }
        self._id = id
        self._prospection_id = prospection_id
        self._message = message
        self.__date = _date

    @classmethod
    def from_dict(cls, dikt) -> 'Note':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Note of this Note.  # noqa: E501
        :rtype: Note
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Note.


        :return: The id of this Note.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Note.


        :param id: The id of this Note.
        :type id: int
        """

        self._id = id

    @property
    def prospection_id(self) -> int:
        """Gets the prospection_id of this Note.


        :return: The prospection_id of this Note.
        :rtype: int
        """
        return self._prospection_id

    @prospection_id.setter
    def prospection_id(self, prospection_id: int):
        """Sets the prospection_id of this Note.


        :param prospection_id: The prospection_id of this Note.
        :type prospection_id: int
        """

        self._prospection_id = prospection_id

    @property
    def message(self) -> str:
        """Gets the message of this Note.


        :return: The message of this Note.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this Note.


        :param message: The message of this Note.
        :type message: str
        """

        self._message = message

    @property
    def _date(self) -> date:
        """Gets the _date of this Note.


        :return: The _date of this Note.
        :rtype: date
        """
        return self.__date

    @_date.setter
    def _date(self, _date: date):
        """Sets the _date of this Note.


        :param _date: The _date of this Note.
        :type _date: date
        """

        self.__date = _date
