# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.prospect_request_prospect import ProspectRequestProspect  # noqa: F401,E501
from swagger_server.models.user import User  # noqa: F401,E501
from swagger_server import util


class ProspectRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, user: User=None, prospect: ProspectRequestProspect=None):  # noqa: E501
        """ProspectRequest - a model defined in Swagger

        :param user: The user of this ProspectRequest.  # noqa: E501
        :type user: User
        :param prospect: The prospect of this ProspectRequest.  # noqa: E501
        :type prospect: ProspectRequestProspect
        """
        self.swagger_types = {
            'user': User,
            'prospect': ProspectRequestProspect
        }

        self.attribute_map = {
            'user': 'user',
            'prospect': 'prospect'
        }
        self._user = user
        self._prospect = prospect

    @classmethod
    def from_dict(cls, dikt) -> 'ProspectRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProspectRequest of this ProspectRequest.  # noqa: E501
        :rtype: ProspectRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user(self) -> User:
        """Gets the user of this ProspectRequest.


        :return: The user of this ProspectRequest.
        :rtype: User
        """
        return self._user

    @user.setter
    def user(self, user: User):
        """Sets the user of this ProspectRequest.


        :param user: The user of this ProspectRequest.
        :type user: User
        """

        self._user = user

    @property
    def prospect(self) -> ProspectRequestProspect:
        """Gets the prospect of this ProspectRequest.


        :return: The prospect of this ProspectRequest.
        :rtype: ProspectRequestProspect
        """
        return self._prospect

    @prospect.setter
    def prospect(self, prospect: ProspectRequestProspect):
        """Sets the prospect of this ProspectRequest.


        :param prospect: The prospect of this ProspectRequest.
        :type prospect: ProspectRequestProspect
        """

        self._prospect = prospect
