# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ProspectUpdate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id_number: str=None, estado: int=None, fecha_modificacion: date=None):  # noqa: E501
        """ProspectUpdate - a model defined in Swagger

        :param id_number: The id_number of this ProspectUpdate.  # noqa: E501
        :type id_number: str
        :param estado: The estado of this ProspectUpdate.  # noqa: E501
        :type estado: int
        :param fecha_modificacion: The fecha_modificacion of this ProspectUpdate.  # noqa: E501
        :type fecha_modificacion: date
        """
        self.swagger_types = {
            'id_number': str,
            'estado': int,
            'fecha_modificacion': date
        }

        self.attribute_map = {
            'id_number': 'id_number',
            'estado': 'estado',
            'fecha_modificacion': 'fecha_modificacion'
        }
        self._id_number = id_number
        self._estado = estado
        self._fecha_modificacion = fecha_modificacion

    @classmethod
    def from_dict(cls, dikt) -> 'ProspectUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProspectUpdate of this ProspectUpdate.  # noqa: E501
        :rtype: ProspectUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id_number(self) -> str:
        """Gets the id_number of this ProspectUpdate.


        :return: The id_number of this ProspectUpdate.
        :rtype: str
        """
        return self._id_number

    @id_number.setter
    def id_number(self, id_number: str):
        """Sets the id_number of this ProspectUpdate.


        :param id_number: The id_number of this ProspectUpdate.
        :type id_number: str
        """

        self._id_number = id_number

    @property
    def estado(self) -> int:
        """Gets the estado of this ProspectUpdate.


        :return: The estado of this ProspectUpdate.
        :rtype: int
        """
        return self._estado

    @estado.setter
    def estado(self, estado: int):
        """Sets the estado of this ProspectUpdate.


        :param estado: The estado of this ProspectUpdate.
        :type estado: int
        """

        self._estado = estado

    @property
    def fecha_modificacion(self) -> date:
        """Gets the fecha_modificacion of this ProspectUpdate.


        :return: The fecha_modificacion of this ProspectUpdate.
        :rtype: date
        """
        return self._fecha_modificacion

    @fecha_modificacion.setter
    def fecha_modificacion(self, fecha_modificacion: date):
        """Sets the fecha_modificacion of this ProspectUpdate.


        :param fecha_modificacion: The fecha_modificacion of this ProspectUpdate.
        :type fecha_modificacion: date
        """

        self._fecha_modificacion = fecha_modificacion
