# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ProspectRequestProspect(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id_number: str=None, state: int=None, company: str=None, id_city: int=None, degree: str=None):  # noqa: E501
        """ProspectRequestProspect - a model defined in Swagger

        :param id_number: The id_number of this ProspectRequestProspect.  # noqa: E501
        :type id_number: str
        :param state: The state of this ProspectRequestProspect.  # noqa: E501
        :type state: int
        :param company: The company of this ProspectRequestProspect.  # noqa: E501
        :type company: str
        :param id_city: The id_city of this ProspectRequestProspect.  # noqa: E501
        :type id_city: int
        :param degree: The degree of this ProspectRequestProspect.  # noqa: E501
        :type degree: str
        """
        self.swagger_types = {
            'id_number': str,
            'state': int,
            'company': str,
            'id_city': int,
            'degree': str
        }

        self.attribute_map = {
            'id_number': 'id_number',
            'state': 'state',
            'company': 'company',
            'id_city': 'id_city',
            'degree': 'degree'
        }
        self._id_number = id_number
        self._state = state
        self._company = company
        self._id_city = id_city
        self._degree = degree

    @classmethod
    def from_dict(cls, dikt) -> 'ProspectRequestProspect':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProspectRequest_prospect of this ProspectRequestProspect.  # noqa: E501
        :rtype: ProspectRequestProspect
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id_number(self) -> str:
        """Gets the id_number of this ProspectRequestProspect.


        :return: The id_number of this ProspectRequestProspect.
        :rtype: str
        """
        return self._id_number

    @id_number.setter
    def id_number(self, id_number: str):
        """Sets the id_number of this ProspectRequestProspect.


        :param id_number: The id_number of this ProspectRequestProspect.
        :type id_number: str
        """

        self._id_number = id_number

    @property
    def state(self) -> int:
        """Gets the state of this ProspectRequestProspect.


        :return: The state of this ProspectRequestProspect.
        :rtype: int
        """
        return self._state

    @state.setter
    def state(self, state: int):
        """Sets the state of this ProspectRequestProspect.


        :param state: The state of this ProspectRequestProspect.
        :type state: int
        """

        self._state = state

    @property
    def company(self) -> str:
        """Gets the company of this ProspectRequestProspect.

        Name of the company associated with the prospect  # noqa: E501

        :return: The company of this ProspectRequestProspect.
        :rtype: str
        """
        return self._company

    @company.setter
    def company(self, company: str):
        """Sets the company of this ProspectRequestProspect.

        Name of the company associated with the prospect  # noqa: E501

        :param company: The company of this ProspectRequestProspect.
        :type company: str
        """

        self._company = company

    @property
    def id_city(self) -> int:
        """Gets the id_city of this ProspectRequestProspect.

        ID of the associated city  # noqa: E501

        :return: The id_city of this ProspectRequestProspect.
        :rtype: int
        """
        return self._id_city

    @id_city.setter
    def id_city(self, id_city: int):
        """Sets the id_city of this ProspectRequestProspect.

        ID of the associated city  # noqa: E501

        :param id_city: The id_city of this ProspectRequestProspect.
        :type id_city: int
        """

        self._id_city = id_city

    @property
    def degree(self) -> str:
        """Gets the degree of this ProspectRequestProspect.

        Degree or title of the prospect  # noqa: E501

        :return: The degree of this ProspectRequestProspect.
        :rtype: str
        """
        return self._degree

    @degree.setter
    def degree(self, degree: str):
        """Sets the degree of this ProspectRequestProspect.

        Degree or title of the prospect  # noqa: E501

        :param degree: The degree of this ProspectRequestProspect.
        :type degree: str
        """

        self._degree = degree
