# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.user import User  # noqa: F401,E501
from swagger_server import util


class ProspectWithUser(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, id_number: str=None, estado: int=None, fecha_creacion: date=None, fecha_modificacion: date=None, user: User=None):  # noqa: E501
        """ProspectWithUser - a model defined in Swagger

        :param id: The id of this ProspectWithUser.  # noqa: E501
        :type id: int
        :param id_number: The id_number of this ProspectWithUser.  # noqa: E501
        :type id_number: str
        :param estado: The estado of this ProspectWithUser.  # noqa: E501
        :type estado: int
        :param fecha_creacion: The fecha_creacion of this ProspectWithUser.  # noqa: E501
        :type fecha_creacion: date
        :param fecha_modificacion: The fecha_modificacion of this ProspectWithUser.  # noqa: E501
        :type fecha_modificacion: date
        :param user: The user of this ProspectWithUser.  # noqa: E501
        :type user: User
        """
        self.swagger_types = {
            'id': int,
            'id_number': str,
            'estado': int,
            'fecha_creacion': date,
            'fecha_modificacion': date,
            'user': User
        }

        self.attribute_map = {
            'id': 'id',
            'id_number': 'id_number',
            'estado': 'estado',
            'fecha_creacion': 'fecha_creacion',
            'fecha_modificacion': 'fecha_modificacion',
            'user': 'user'
        }
        self._id = id
        self._id_number = id_number
        self._estado = estado
        self._fecha_creacion = fecha_creacion
        self._fecha_modificacion = fecha_modificacion
        self._user = user

    @classmethod
    def from_dict(cls, dikt) -> 'ProspectWithUser':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProspectWithUser of this ProspectWithUser.  # noqa: E501
        :rtype: ProspectWithUser
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this ProspectWithUser.


        :return: The id of this ProspectWithUser.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this ProspectWithUser.


        :param id: The id of this ProspectWithUser.
        :type id: int
        """

        self._id = id

    @property
    def id_number(self) -> str:
        """Gets the id_number of this ProspectWithUser.


        :return: The id_number of this ProspectWithUser.
        :rtype: str
        """
        return self._id_number

    @id_number.setter
    def id_number(self, id_number: str):
        """Sets the id_number of this ProspectWithUser.


        :param id_number: The id_number of this ProspectWithUser.
        :type id_number: str
        """

        self._id_number = id_number

    @property
    def estado(self) -> int:
        """Gets the estado of this ProspectWithUser.


        :return: The estado of this ProspectWithUser.
        :rtype: int
        """
        return self._estado

    @estado.setter
    def estado(self, estado: int):
        """Sets the estado of this ProspectWithUser.


        :param estado: The estado of this ProspectWithUser.
        :type estado: int
        """

        self._estado = estado

    @property
    def fecha_creacion(self) -> date:
        """Gets the fecha_creacion of this ProspectWithUser.


        :return: The fecha_creacion of this ProspectWithUser.
        :rtype: date
        """
        return self._fecha_creacion

    @fecha_creacion.setter
    def fecha_creacion(self, fecha_creacion: date):
        """Sets the fecha_creacion of this ProspectWithUser.


        :param fecha_creacion: The fecha_creacion of this ProspectWithUser.
        :type fecha_creacion: date
        """

        self._fecha_creacion = fecha_creacion

    @property
    def fecha_modificacion(self) -> date:
        """Gets the fecha_modificacion of this ProspectWithUser.


        :return: The fecha_modificacion of this ProspectWithUser.
        :rtype: date
        """
        return self._fecha_modificacion

    @fecha_modificacion.setter
    def fecha_modificacion(self, fecha_modificacion: date):
        """Sets the fecha_modificacion of this ProspectWithUser.


        :param fecha_modificacion: The fecha_modificacion of this ProspectWithUser.
        :type fecha_modificacion: date
        """

        self._fecha_modificacion = fecha_modificacion

    @property
    def user(self) -> User:
        """Gets the user of this ProspectWithUser.


        :return: The user of this ProspectWithUser.
        :rtype: User
        """
        return self._user

    @user.setter
    def user(self, user: User):
        """Sets the user of this ProspectWithUser.


        :param user: The user of this ProspectWithUser.
        :type user: User
        """

        self._user = user
