# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ProspectUpdate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, state: int=None, first_name: str=None, last_name: str=None, email: str=None, phone: str=None, company: str=None):  # noqa: E501
        """ProspectUpdate - a model defined in Swagger

        :param state: The state of this ProspectUpdate.  # noqa: E501
        :type state: int
        :param first_name: The first_name of this ProspectUpdate.  # noqa: E501
        :type first_name: str
        :param last_name: The last_name of this ProspectUpdate.  # noqa: E501
        :type last_name: str
        :param email: The email of this ProspectUpdate.  # noqa: E501
        :type email: str
        :param phone: The phone of this ProspectUpdate.  # noqa: E501
        :type phone: str
        :param company: The company of this ProspectUpdate.  # noqa: E501
        :type company: str
        """
        self.swagger_types = {
            'state': int,
            'first_name': str,
            'last_name': str,
            'email': str,
            'phone': str,
            'company': str
        }

        self.attribute_map = {
            'state': 'state',
            'first_name': 'first_name',
            'last_name': 'last_name',
            'email': 'email',
            'phone': 'phone',
            'company': 'company'
        }
        self._state = state
        self._first_name = first_name
        self._last_name = last_name
        self._email = email
        self._phone = phone
        self._company = company

    @classmethod
    def from_dict(cls, dikt) -> 'ProspectUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProspectUpdate of this ProspectUpdate.  # noqa: E501
        :rtype: ProspectUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def state(self) -> int:
        """Gets the state of this ProspectUpdate.


        :return: The state of this ProspectUpdate.
        :rtype: int
        """
        return self._state

    @state.setter
    def state(self, state: int):
        """Sets the state of this ProspectUpdate.


        :param state: The state of this ProspectUpdate.
        :type state: int
        """

        self._state = state

    @property
    def first_name(self) -> str:
        """Gets the first_name of this ProspectUpdate.


        :return: The first_name of this ProspectUpdate.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name: str):
        """Sets the first_name of this ProspectUpdate.


        :param first_name: The first_name of this ProspectUpdate.
        :type first_name: str
        """

        self._first_name = first_name

    @property
    def last_name(self) -> str:
        """Gets the last_name of this ProspectUpdate.


        :return: The last_name of this ProspectUpdate.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name: str):
        """Sets the last_name of this ProspectUpdate.


        :param last_name: The last_name of this ProspectUpdate.
        :type last_name: str
        """

        self._last_name = last_name

    @property
    def email(self) -> str:
        """Gets the email of this ProspectUpdate.


        :return: The email of this ProspectUpdate.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this ProspectUpdate.


        :param email: The email of this ProspectUpdate.
        :type email: str
        """

        self._email = email

    @property
    def phone(self) -> str:
        """Gets the phone of this ProspectUpdate.


        :return: The phone of this ProspectUpdate.
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone: str):
        """Sets the phone of this ProspectUpdate.


        :param phone: The phone of this ProspectUpdate.
        :type phone: str
        """

        self._phone = phone

    @property
    def company(self) -> str:
        """Gets the company of this ProspectUpdate.

        Name of the company associated with the prospect  # noqa: E501

        :return: The company of this ProspectUpdate.
        :rtype: str
        """
        return self._company

    @company.setter
    def company(self, company: str):
        """Sets the company of this ProspectUpdate.

        Name of the company associated with the prospect  # noqa: E501

        :param company: The company of this ProspectUpdate.
        :type company: str
        """

        self._company = company
