# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ProspectionRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id_academic_program: int=None, id_prospect: int=None, fecha: date=None, estado: int=None):  # noqa: E501
        """ProspectionRequest - a model defined in Swagger

        :param id_academic_program: The id_academic_program of this ProspectionRequest.  # noqa: E501
        :type id_academic_program: int
        :param id_prospect: The id_prospect of this ProspectionRequest.  # noqa: E501
        :type id_prospect: int
        :param fecha: The fecha of this ProspectionRequest.  # noqa: E501
        :type fecha: date
        :param estado: The estado of this ProspectionRequest.  # noqa: E501
        :type estado: int
        """
        self.swagger_types = {
            'id_academic_program': int,
            'id_prospect': int,
            'fecha': date,
            'estado': int
        }

        self.attribute_map = {
            'id_academic_program': 'id_academic_program',
            'id_prospect': 'id_prospect',
            'fecha': 'fecha',
            'estado': 'estado'
        }
        self._id_academic_program = id_academic_program
        self._id_prospect = id_prospect
        self._fecha = fecha
        self._estado = estado

    @classmethod
    def from_dict(cls, dikt) -> 'ProspectionRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProspectionRequest of this ProspectionRequest.  # noqa: E501
        :rtype: ProspectionRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id_academic_program(self) -> int:
        """Gets the id_academic_program of this ProspectionRequest.


        :return: The id_academic_program of this ProspectionRequest.
        :rtype: int
        """
        return self._id_academic_program

    @id_academic_program.setter
    def id_academic_program(self, id_academic_program: int):
        """Sets the id_academic_program of this ProspectionRequest.


        :param id_academic_program: The id_academic_program of this ProspectionRequest.
        :type id_academic_program: int
        """

        self._id_academic_program = id_academic_program

    @property
    def id_prospect(self) -> int:
        """Gets the id_prospect of this ProspectionRequest.


        :return: The id_prospect of this ProspectionRequest.
        :rtype: int
        """
        return self._id_prospect

    @id_prospect.setter
    def id_prospect(self, id_prospect: int):
        """Sets the id_prospect of this ProspectionRequest.


        :param id_prospect: The id_prospect of this ProspectionRequest.
        :type id_prospect: int
        """

        self._id_prospect = id_prospect

    @property
    def fecha(self) -> date:
        """Gets the fecha of this ProspectionRequest.


        :return: The fecha of this ProspectionRequest.
        :rtype: date
        """
        return self._fecha

    @fecha.setter
    def fecha(self, fecha: date):
        """Sets the fecha of this ProspectionRequest.


        :param fecha: The fecha of this ProspectionRequest.
        :type fecha: date
        """

        self._fecha = fecha

    @property
    def estado(self) -> int:
        """Gets the estado of this ProspectionRequest.


        :return: The estado of this ProspectionRequest.
        :rtype: int
        """
        return self._estado

    @estado.setter
    def estado(self, estado: int):
        """Sets the estado of this ProspectionRequest.


        :param estado: The estado of this ProspectionRequest.
        :type estado: int
        """

        self._estado = estado
